interface Info {
  currentTime: number;
  network: string;
  name: string;
  stateType: string;
  difficulty: number;
  bestFullHeaderId: string;
  bestHeaderId: string;
  peersCount: number;
  unconfirmedCount: number;
  appVersion: string;
  eip37Supported: boolean;
  stateRoot: string;
  genesisBlockId: string;
  previousFullHeaderId: string;
  fullHeight: number;
  headersHeight: number;
  stateVersion: string;
  fullBlocksScore: number;
  maxPeerHeight: number;
  launchTime: number;
  isExplorer: boolean;
  lastSeenMessageTime: number;
  eip27Supported: boolean;
  headersScore: number;
  parameters: {
    outputCost: number;
    tokenAccessCost: number;
    maxBlockCost: number;
    height: number;
    maxBlockSize: number;
    dataInputCost: number;
    blockVersion: number;
    inputCost: number;
    storageFeeFactor: number;
    minValuePerByte: number;
  };
  isMining: boolean;
}
